public class ChallengeTwo {
   public void ForLoop() {
       List <integer> name = new List <integer>{1,2,3,4,5,6,7,8,9,10};
           For(integer num:name){
               system.debug(num);
           }
           
    }
    public void WhileLoop() {
        integer I = 0;
        
        while(I <11){
            system.debug(I);
            I++;
        } 
        
        
    }
    public void Iffy() {
        Boolean var =false;
        integer i = 4;
        if(var == true){
            system.debug('eeeee');
        }else if(i==4){
           system.debug('Whaaat'); 
        }
            
        
        
    }
   
   
    
}